stages:
  - test
  - build
  - deploy

test:
  image: alpine:latest
  stage: test
  script:
    - "apk update"
    - "apk add yarn zip"
    - "yarn"
    - "yarn test"

build:
  image: alpine:latest
  stage: build
  script:
    - "apk update"
    - "apk add zip"
    - "zip -rj key_rotator.zip src/*"
  artifacts:
    paths:
      - key_rotator.zip

deploy:
  image: hashicorp/terraform:light
  stage: deploy
  script:
    - "ls"
    - "export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
    - "export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY"
    - "export AWS_DEFAULT_REGION=us-east-1"
    - "terraform init -reconfigure -input=false"
    - "terraform validate -input=false -var gitlab_group_id=$GROUP_ID -var api_key=$API_KEY"
    - "terraform apply -input=false -auto-approve -var gitlab_group_id=$GROUP_ID -var api_key=$API_KEY"