stages:
  - test_build
  - deploy

test:
  image: alpine:latest
  stage: test_build
  script:
    - "apk update"
    - "apk add yarn zip"
    - "yarn"
    - "yarn test"

build:
  image: alpine:latest
  stage: test_build
  script:
    - "apk update"
    - "apk add yarn zip"
    - "yarn"
    - "zip -r key_rotator.zip ./*"
  artifacts:
    paths:
      - key_rotator.zip


deploy:
  image:
    name: hashicorp/terraform:light
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'
  stage: deploy
  only:
    - master
  script:
    - "export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
    - "export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY"
    - "export AWS_DEFAULT_REGION=us-east-1"
    - "terraform init -reconfigure -input=false"
    - "terraform workspace select dev || terraform workspace new dev"
    - "terraform validate -input=false -var gitlab_group_id=$GROUP_ID -var api_key=$API_KEY"
    - "terraform apply -input=false -auto-approve -var gitlab_group_id=$GROUP_ID -var api_key=$API_KEY"
